name: Sync Fork

on:
  schedule:
    - cron: '15 2 1 * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1
        with:
          owner: mayswind
          base: master
          head: master
          merge_method: rebase
